_BASE_: "../../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/CUSTOM_faster_rcnn_R_101_FPN_base3/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 7
    OUTPUT_LAYER: "CosineSimOutputLayers"
    COSINE_SCALE: 20.0
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('aquarium_2007_trainval_novel3_1shot',)
  TEST: ('aquarium_2007_test_novel3',)
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.001
  STEPS: (70,)
  MAX_ITER: 200
  CHECKPOINT_PERIOD: 100
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/CUSTOM_faster_rcnn_R_101_FPN_ft_normalized_all3_1shot_randnovel_1scale"