DATASETS:
  TEST: !!python/tuple
  - voc_2007_test_all3
  TRAIN: !!python/tuple
  - voc_2007_trainval_all3_1shot_seed9
INPUT:
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: false
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    FREEZE_FEAT: true
    NUM_CLASSES: 20
    OUTPUT_LAYER: CosineSimOutputLayers
  WEIGHTS: checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base3/model_reset_surgery.pth
OUTPUT_DIR: ./checkpoints/voc/faster_rcnn/seed9/faster_rcnn_R_101_FPN_ft_all3_1shot
SOLVER:
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 400
  IMS_PER_BATCH: 16
  MAX_ITER: 4000
  STEPS: !!python/tuple
  - 3500
  WARMUP_ITERS: 0
_BASE_: ../../../Base-RCNN-FPN.yaml
